name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  go-ci:
    name: Go CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24.5'
      - name: Vet and Lint
        run: |
          go fmt ./...
          go vet ./...
      - name: Run Tests
        run: go test -v ./...

  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Check Formatting
        run: cargo fmt --all -- --check
        working-directory: ./agent-rs
      - name: Clippy Linting
        run: cargo clippy -- -D warnings
        working-directory: ./agent-rs
      - name: Run Tests
        run: cargo test --verbose
        working-directory: ./agent-rs